tf.concat(tensorA, tensorB) should throw an error

Environment info
Operating System: Ubuntu 15.10
CPU-only pip package, version 0.7.1
Steps to reproduce
import tensorflow as tf
a = tf.Variable(tf.constant(1.0, shape=[10]))
b = tf.Variable(tf.constant(2.0, shape=[10]))
print tf.concat(a, b) # <tf.Tensor 'concat:0' shape=(10,) dtype=float32>

Since the second argument to concat can be converted into a list of length 1, tensorflow takes a fast-path and immediately returns it, before type-checking the first argument. I would have expected an error that enabled me to find my incorrect API usage.