image_ops_test failing due to math_ops.sin() behaving differently

System information

Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
TensorFlow installed from (source or binary): Source
TensorFlow version (use command below): v1.2.1
Python version: 2.7.12
Bazel version (if compiling from source): 0.4.5
CUDA/cuDNN version: No GPU
GPU model and memory: No GPU
Exact command to reproduce: bazel test -c opt //tensorflow/contrib/image:image_ops_test

Describe the problem
The above test fails with the output array mismatch in test_rotate_even.
The exact cause of failure seems to be at math_ops.sin(angles), which only fails for angle=(np.pi / 4.0) = 0.78539819 (45 deg) and works fine for 0 and 90 deg.
The output of math_ops.sin(0.78539819).eval() differs on Intel and s390x as below:

Intel(test passes) : 0.707106769
s390x(test fails) : 0.707106829

I verified np.sin(0.78539819) gives same output 0.7071067999 on both Intel and s390x.
Why is the difference seen in math_ops.sin()? Any pointers would be helpful.
Source logs

FAIL: test_rotate_even (main.ImageOpsTest)
Traceback (most recent call last):
  File "/home/test/.cache/bazel/_bazel_test/24685d064c07f7346b48c2d13ec3ad69/execroot/tensorflow/bazel-out/local-opt/bin/tensorflow/contrib/image/image_ops_test.runfiles/org_tensorflow/tensorflow/contrib/image/python/kernel_tests/image_ops_test.py", line 75, in test_rotate_even
    [1, 7, 13, 19, 25, 31], [0, 6, 12, 18, 24, 30]]])
  File "/home/test/.cache/bazel/_bazel_test/24685d064c07f7346b48c2d13ec3ad69/execroot/tensorflow/bazel-out/local-opt/bin/tensorflow/contrib/image/image_ops_test.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 699, in assertAllEqual
    np.testing.assert_array_equal(a, b)
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 807, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 733, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not equal

(mismatch 1.85185185185%)
 x: array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],...
 y: array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],...

not equal where =  (array([1, 1]), array([3, 4]), array([3, 4]))
not equal lhs =  [20 32]
not equal rhs =  [21 33]