tf.contrib.memory_stats.MaxBytesInUse() got `Op type not registered 'MaxBytesInUse' in binary running` error

System information

Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Should be Yes, as subtitle Source code below.
OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Windows 7 x64
TensorFlow installed from (source or binary):
pip install tensorflow-gpu with Anaconda on windows prompt following the tensorflow official tutorial
TensorFlow version (use command below):
tensorflow-gpu 1.4.0
Python version:
3.6, Anaconda
Bazel version (if compiling from source):
N/A
CUDA/cuDNN version:
8.0/6.0
GPU model and memory:
GTX 1080TI
Exact command to reproduce:
a simply python code.py or following source in python

Describe the problem
The GPU training is all fine on my placement.
But when I wanna track the memory usage I got the error using MaxBytesInUse(),
the problem is not solved even I upgrade TF from 1.3 to 1.4.
And of course the same error using BytesInUse().
Is any solution or is the possibility that the method not support for Win7? Thanks.
Source code / logs
The Op created failed even the simple code execute as follow, when I run MaxBytesInUse() to get a tensor to a then it failed.
import tensorflow as tf
a = tf.contrib.memory_stats.MaxBytesInUse()

And got the message
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\my\Anaconda3\lib\site-packages\tensorflow\contrib\memory_stats\python\ops\memory_stats_ops.py", line 41, in MaxBytesInUse
    return gen_memory_stats_ops.max_bytes_in_use()
  File "C:\Users\my\Anaconda3\lib\site-packages\tensorflow\contrib\memory_stats\ops\gen_memory_stats_ops.py", line 88, in max_bytes_in_use
    "MaxBytesInUse", name=name)
  File "C:\Users\my\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\my\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2958, in create_op
    set_shapes_for_outputs(ret)
  File "C:\Users\my\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2209, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "C:\Users\my\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2159, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "C:\Users\my\Anaconda3\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 627, in call_cpp_shape_fn
    require_shape_fn)
  File "C:\Users\my\Anaconda3\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 686, in _call_cpp_shape_fn_impl
    input_tensors_as_shapes, status)
  File "C:\Users\my\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'MaxBytesInUse' in binary running on MY-PC. Make sure the Op and Kernel are registered in the binary running in this process.