GTX 1080 Ti Cuda Launch Failed

Please go to Stack Overflow for help and support:
http://stackoverflow.com/questions/tagged/tensorflow
If you open a GitHub issue, here is our policy:

It must be a bug or a feature request.
The form below must be filled out.
It shouldn't be a TensorBoard issue. Those go here.

Here's why we have that policy: TensorFlow developers respond to issues. We want to focus on work that benefits the whole community, e.g., fixing bugs and adding features. Support only helps individuals. GitHub also notifies thousands of people when issues are filed. We want them to see you communicating an interesting problem, rather than being redirected to Stack Overflow.

System information


Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
No


OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Linux Ubuntu 16.04


TensorFlow installed from (source or binary):
Source


TensorFlow version (use command below):
('v1.1.0-rc2-9-gb7f85a7', '1.1.0-rc1')


Bazel version (if compiling from source):
Bazel Release 0.5.0


CUDA/cuDNN version:
Cuda 8.0 cuDNN 8.0


GPU model and memory:
GTX 1080Ti - 11GB memory


Exact command to reproduce:


bazel-bin/inception/flowers_train 
--train_dir="${TRAIN_DIR}" 
--data_dir="${DATA_DIR}" 
--pretrained_model_checkpoint_path="${MODEL_PATH}" 
--fine_tune=True 
--initial_learning_rate=0.001 
--input_queue_memory_factor=2
You can collect some of this information using our environment capture script:
https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh
tf_env.txt
You can obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.
When fine tuning inception v3 model using the flowers data script, on custom data, during retraining I see the following error:
2017-06-19 23:46:32.549857: step 5300, loss = 1.40 (61.9 examples/sec; 0.517 sec/batch)
2017-06-19 23:46:39.510009: step 5310, loss = 1.43 (64.2 examples/sec; 0.499 sec/batch)
2017-06-19 23:46:44.667435: step 5320, loss = 1.55 (64.3 examples/sec; 0.498 sec/batch)
2017-06-19 23:46:46.691129: E tensorflow/stream_executor/cuda/cuda_driver.cc:1067] could not synchronize on CUDA context: CUDA_ERROR_LAUNCH_FAILED :: No stack trace available
2017-06-19 23:46:46.691129: E tensorflow/stream_executor/cuda/cuda_event.cc:49] Error polling for event status: failed to query event: CUDA_ERROR_LAUNCH_FAILED
2017-06-19 23:46:46.691162: F tensorflow/core/common_runtime/gpu/gpu_event_mgr.cc:203] Unexpected Event status: 1
2017-06-19 23:46:46.691165: F tensorflow/core/common_runtime/gpu/gpu_util.cc:370] GPU sync failed
./start_image.sh: line 60: 27406 Aborted                 (core dumped) bazel-bin/inception/flowers_train --train_dir="${TRAIN_DIR}" --data_dir="${DATA_DIR}" --pretrained_model_checkpoint_path="${MODEL_PATH}" --fine_tune=True --initial_learning_rate=0.001 --input_queue_memory_factor=2
I changed the num classes and num examples per epoch as follows:
7    def num_classes(self):
8      """Returns the number of classes in the data set."""
9 -    return 5
10 +    return 21
11
12    def num_examples_per_epoch(self):
13      """Returns the number of examples in the data subset."""
14      if self.subset == 'train':
15 -      return 3170
16 +      return 6342
17      if self.subset == 'validation':
18 -      return 500
19 +      return 1576
Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.