Tensorflow retrain.py random distortions

Environment info
Operating System: Mac OS X with Tensorflow 0.8 installed.
I am trying to run retrain.py with my custom training set, but whenever I try passing in the argument --random_crop 5 when running retrain.py the program errors out and says:

tensorflow.python.framework.errors.InvalidArgumentError: assertion failed: [Need value.shape >= size, got ] [314 314 1] [299 299 3]
[[Node: random_crop/Assert = [Assert T=[DT_STRING, DT_INT32, DT_INT32], summarize=3, _device="/job:localhost/replica:0/task:0/cpu:0"(random_crop/All, random_crop/Assert/data_0, random_crop/Shape, random_crop/size)]]
Caused by op u'random_crop/Assert'

The command I am using is:
bazel-bin/tensorflow/examples/image_retraining/retrain --image_dir /path/to/my/training_images --how_many_training_steps 5000 --random_crop 5
Is this an issue with the size of the images that I am using for my training set?